
services:
  netsuite-printing:
    container_name: netsuite-printing
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1000:1000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./src:/app/src 
    stdin_open: true
    tty: true
